// This program creats a loop generated by SW0 (A17)'s slide-switch position from off
// to on.  When the switch is turned to "on", a series of functions initializations and 
// calls. Some of these function include UART initialization, others prompt a user for 
// user input. The program ends and terminates from the user switching LED 0's
// position. When the switch is hit to off, the functions end, and the main function No-
// op's. When the switch is hit back on, the entire user entry to prime number 
// calculations occurs again to update LED light output.


// LIBRARIES
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <errno.h> // For errno and ERANGE, this was from Google Gemini last second
#include <limits.h> // For LONG_MAX, LONG_MIN, this was from Google Gemini last second
#include "sleep.h"
#include "xil_printf.h"
// DEFINITIONS
#define UART1_CR *((volatile uint32_t *)0xE0001000) // UART1 control register
#define UART1_MR *((volatile uint32_t *)0xE0001004) // UART1 mode register
#define UART1_BAUDGEN *((volatile uint32_t *)0xE0001018) // UART1 baud rate generator
#define UART1_BAUDDIV *((volatile uint32_t *)0xE0001034) // UART1 baud rate divider
#define UART1_SR *((volatile uint32_t *)0xE000102C) // UART1 status register
#define UART1_DATA *((volatile uint32_t *)0xE0001030) // UART1 TX/RX FIFO data
#define LED_DATA *((volatile uint32_t *)0x41210000) // LEDs (lower 10 bits)
#define SW_DATA *((volatile uint32_t *)0x41220000) // Switches (lower 12 bits)
#define BaudGen115200 0x7c // For 115200 bps with 100 MHz clock
#define BaudDiv115200 6
#define AUTO_OUTPUT_DELAY_US 420000 // 0.42 seconds delay for automated outputs
#define MAX_DOTS 42 // How many dots before wrapping around
#define RX_TIMEOUT_LOOPS 5000000 // Max loops for RX timeout (e.g., ~5 seconds)

// UART
bool uart1_tx_full() { // Check if TX FIFO is full.
 return (UART1_SR & 0x10) != 0; // Bit 4 = TX FIFO full.
}
void uart1_put_char(char c) { // Send a single character to the UART FIFO TX buffer.
 while (uart1_tx_full()); // Wait until TX FIFO is not full.
 UART1_DATA = c; // Write character to TX FIFO.
}
bool uart1_rx_data_ready() { // Check if RX FIFO has data (bit 3).
 return (UART1_SR & 0x08) != 0;
}
// Receive a single character from the console with a timeout.
// Returns character (as int) on success, -1 on timeout.
int uart1_get_char_timeout() {
 volatile int timeout_counter = 0;
 while (!uart1_rx_data_ready()) {
 if (timeout_counter++ >= RX_TIMEOUT_LOOPS) {
 return -1; // Timeout occurred
 }
 // Small delay to prevent busy-waiting too aggressively on very fast CPUs.
}

 return (int)(UART1_DATA & 0xFF); // Read byte from RX FIFO.
}
void uart1_putstr(const char *str) { // Send a string over UART.
 while (*str) {
 uart1_put_char(*str++);
 }
}
void int_to_str(int num, char *str) { // Convert integer to string.
 // Handles 0 explicitly.
 if (num == 0) {
 str[0] = '0';
 str[1] = '\0';
 return;
 }
 int i = 0;
 char temp[12]; // Buffer for conversion (max digit count including null, 12 digits).
 while (num > 0) {
 temp[i++] = (num % 10) + '0'; // Convert digits in reverse order, this was CoPilot’s
// idea.
 num /= 10;
 }
 int j;

 // Reverse the digits from 'temp' into 'str' to get correct order,
 // (e.g., '3','2','1' reversed to '1','2','3').
 for (j = 0; j < i; j++) {
 str[j] = temp[i - j - 1];
 }
 str[i] = '\0'; // Null-terminate the resulting string.
}
bool is_prime(int number) { // Check if a number is prime.
 if (number == 2) return true; // Trivial logic for lab restrictions.
 if (number <= 1 || (number % 2 == 0)) return false; // Trivial logic for lab restrictions.
 for (int i = 3; i * i <= number; i += 2) {
 if (number % i == 0) return false; // Trivial logic for lab restrictions.
 }
 return true;
}
// Find closest prime number below input.
int closest_prime(int n) { // Initiate the count down process.
 while (n > 1 && !is_prime(n)) { // While N is an integer and isn’t prime.
 n--; // Decrease the value of N, for an cycle of rechecking prime status.
 }
 return n; // Return N for the rechecking prime status.
}
int get_integer() { // Get integer input from UART with CoPilots enhanced robustness.

 char buffer[12]; // Max 10 digits for INT_MAX, plus sign and null terminator.
 int index = 0;
 char c;
 long val; // Use long for strtol result.
 char *endptr;
 uart1_putstr("\r\nEnter a integer greater than 3: "); // Just some output for the user.
 while (index < sizeof(buffer) - 1) { // Leave space for null terminator for ASCII.
 int received_char = uart1_get_char_timeout(); // Use timeout version for the FIFO
// buffer.
 if (received_char == -1) { // Timeout, I couldn’t stop Microsoft CoPilot from being
// excessive here, I am learning how to master a free model still.
 uart1_putstr("\r\nInput timeout! Please try again.\r\n");
 return 0; // Return 0 or some error indicator for the application.
 }
 c = (char)received_char;

 // Basic backspace handling, this was Microsoft CoPilots idea…
 if (c == '\b' || c == 0x7F) { // ASCII backspace or delete.

 if (index > 0) {
 index--;
 uart1_putstr("\b \b"); // Erase character from terminal.
 }
 continue; // Skip processing as a digit.
 }
 uart1_put_char(c); // Echo character to terminal.
 if (c == '\r' || c == '\n') { // Enter key from the user console, that’s how we mess with
// putty initially on every console connection, is it not?
 buffer[index] = '\0';
 break;
 }

 // Only accept digits and a single leading minus sign, some logical checks.
 if ((c >= '0' && c <= '9') || (c == '-' && index == 0 && index < sizeof(buffer) - 2)) {
 buffer[index++] = c;
 } else {
 // Ignore non-digit/non-initial-minus characters, checks implemented
// elsewhere.
 }
 }


 buffer[index] = '\0'; // Ensure string is null-terminated even if buffer full, some junk
// garbage AI is inserting, I’m still learning how to successfully use it.
 // Use strtol for safer conversion and error checking.
 errno = 0; // Clear errno before call
 val = strtol(buffer, &endptr, 10);
 // Check for conversion errors, some more crazy crap Microsoft CoPilot wanted to
 // add in that I couldn’t stop and get removed and groomed in time for between
 // copying and pasting.
 if (endptr == buffer || *endptr != '\0') {
 uart1_putstr("\r\nInvalid input: Not a valid number.\r\n");
 return 0; // Or handle as an error
 } else if ((val == LONG_MAX && errno == ERANGE) || (val == LONG_MIN && errno ==
ERANGE)) {
 uart1_putstr("\r\nInput number too large or too small.\r\n");
 return 0; // Or handle as an error
 } else if (val > INT_MAX || val < INT_MIN) { // Check if it fits in 'int'.
 uart1_putstr("\r\nInput number exceeds integer limits.\r\n");
 return 0;
 }
 return (int)val;
}

void reset_uart1() { // Reset UART1.
 UART1_CR = 0x03; // TX and RX FIFO reset, it must be done.
 while (UART1_CR & 0x03); // Wait for resets to clear.
}
void configure_uart1() { // Configure UART1 for 8N1.
 UART1_MR = 0x20; // 8 data bits, no parity, 1 stop bit.
 UART1_CR = 0x03; // Enable TX and RX.
}
void set_baudrate1() { // Set baud rate to 115200.
 UART1_BAUDGEN = BaudGen115200;
 UART1_BAUDDIV = BaudDiv115200;
}
void init_uart1() { // Initialize UART1.
 reset_uart1();
 set_baudrate1();
 configure_uart1();
}

// APPLICATION LOGIC
void print_closest_prime(int input) { // Function to print closest prime number to the
// console.
 if (input < 4) { // Check to continue correctly.
 uart1_putstr("Please enter an integer greater than 3.\r\n");
 } else {
 int prime = closest_prime(input);
 char prime_str[12]; // Sufficient buffer for positive integers.
 int_to_str(prime, prime_str);
 uart1_putstr("Closest prime below your input: ");
 uart1_putstr(prime_str);
 uart1_putstr("\r\n");
 uart1_putstr("\r\nPlease reset the switch to reinitialize the calculator.\r\n");
 }
}

int main(void) {
 init_uart1(); // Initialize UART1.
 // Local variable declarations.
 uint32_t val_sw;
 bool prev_sw0_state = false; // To track if SW0 was ON or OFF in the previous loop
// iteration.
 int dot_count = 0; // To initialize dot_count, best practice!
 static bool has_greeted_this_boot = false; // Flag to ensure "Hello, world!" prints
// only once per program execution.
 // Initial welcome message.
 uart1_putstr("\r\n--- Prime Calculator Initialized. Toggle SW0 to begin ---\r\n");
 while (1) {
 val_sw = SW_DATA;

 bool current_sw0_state = (val_sw & 0x1); // True if SW0 is on.

 if (current_sw0_state) { // SW0 state is on.
 if (!prev_sw0_state) { // If our flagging has not been set:
 // "Hello World!" only on the very first activation after boot.
 if (!has_greeted_this_boot) {
 uart1_putstr("\r\nHello, world!\r\n"); // Print "Hello, world!"
 usleep(AUTO_OUTPUT_DELAY_US);
 has_greeted_this_boot = true; // Set the flag so it doesn't print again this
// boot.
 } else {
 // For subsequent activations (after the first boot greeting), just indicate
// interactive mode.
 uart1_putstr("\r\nSwitch 0 is now on. Entering interactive mode.\r\n");
 usleep(AUTO_OUTPUT_DELAY_US);
 }
 dot_count = 0; // Reset dot count when we switch to on mode.
 }

 LED_DATA = val_sw; // Reflect all switch states on LEDs.
 // Corrected prompt for user input.
 uart1_putstr("\r\nEnter an Integer greater than or equal to 3 to find its closest prime number:\r\n");

 int input = get_integer(); // User interaction happens here.



 if (input == 0) { // Get_integer returns 0 on invalid input or timeout.
 uart1_putstr("Invalid input. Please input an integer greater than or equal to 3.\r\n");
 } else if (input < 3) { // Checks against the user input.
 uart1_putstr("Invalid input. Please input an integer greater than or equal to 3.\r\n");
 } else {
 // If input is valid and >= 3, proceed with prime calculation and success
//message.
 print_closest_prime(input); // This will print the prime and the "reset switch"
// message.
 }

 // New message after any interaction (valid or invalid).
 uart1_putstr("Please reset switch 0 to reset the closest prime number calculator...\r\n");

 // Loop while SW0 is still ON, waiting for user to turn it off.
 while (current_sw0_state) {
 val_sw = SW_DATA; // Continuously read the switch state.
 current_sw0_state = (val_sw & 0x1); // Update current state.
 usleep(100000); // Small delay to debounce and not busy-loop too fast (0.1s).
 }

 } else { // SW0 is currently off logic:
 LED_DATA = 0; // Clear LEDs when SW0 is off.
 if (prev_sw0_state) { // If the switch was previous turned on.
 uart1_putstr("\r\nSwitch 0 is now OFF. Waiting for activation"); // Initial
// message.
 usleep(AUTO_OUTPUT_DELAY_US); // Delay after this initial message.
 dot_count = 0; // Reset dot count.
 }

 uart1_put_char('.'); // Add a dot to the console output.
 dot_count++;
 if (dot_count >= MAX_DOTS) { // If 42 dots have been reached.
 uart1_putstr("\r\nSwitch 0 is now OFF. Waiting for activation"); // Restart the
// message.
 usleep(AUTO_OUTPUT_DELAY_US); // Delay after restarting the message
 dot_count = 0; // Reset dot count for dots.
 }
 usleep(250000); // Quarter-second for dot animation.
 }
 prev_sw0_state = current_sw0_state; // Update the previous state for the next
// loop iteration.
 }
}

/*Clean string creation from i2C SPI: 


void read_accel_xyz(int16_t *x, int16_t *y, int16_t *z) {
    uint8_t rx_buf[6];
    uint8_t reg_addr = OUT_X_L_XL;  // starting address

    spi_read_multi(SS0, reg_addr, rx_buf, 6);

    *x = (rx_buf[1] << 8) | rx_buf[0]; // Junk is added to the first 8 bits
    *y = (rx_buf[3] << 8) | rx_buf[2]; // Junk is added to the first 8 bits
    *z = (rx_buf[5] << 8) | rx_buf[4]; // 
}


void uart_report_accel(int16_t x, int16_t y, int16_t z) {
    char buf[64];
    sprintf(buf, "Accel X=%d Y=%d Z=%d\r\n", x, y, z);
    uart_send(buf); // reusable char* send function
}
*/
